name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}         # e.g., 16.171.36.104
          username: ubuntu                      # default user for Ubuntu EC2
          key: ${{ secrets.EC2_KEY }}           # paste your .pem file content here as a GitHub secret
          script: |
            cd jiitak_DevOps_Intern_Project
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker build -t jiitak-project-flask-app .
            docker run -d -p 5000:5000 jiitak-project-flask-app

