name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/jiitak_DevOps_Intern_Project
            git pull origin main
            docker build -t jiitak-project-flask-app .
            docker stop $(docker ps -q) || true
            docker run -d -p 5000:5000 jiitak-project-flask-app
          EOF
